[latest]
title = "alookso ─ 둘러보기 ─ 최신 글"
url = "https://alook.so/discover/latest"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[trendiest]
title = "alookso ─ 둘러보기 ─ 뜨는 글"
url = "https://alook.so/discover"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/alookso]
title = "alookso ─ alookso"
url = "https://alook.so/users/x4WtnB"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/hyeseung]
title = "alookso ─ 정혜승 대표"
url = "https://alook.so/users/8OgtK8"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/sooyoung]
title = "alookso ─ 윤수영"
url = "https://alook.so/users/xwVtDZ"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/soventure]
title = "alookso ─ 이재웅"
url = "https://alook.so/users/6mt7oo"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/yozoh]
title = "alookso ─ 신요조"
url = "https://alook.so/users/8Ogtd9"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/janghyeyeong]
title = "alookso ─ 장혜영"
url = "https://alook.so/users/8XGtO0"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user/datacow]
title = "alookso ─ 데이터카우"
url = "https://alook.so/users/bA6tp1"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"